name: kwaze_kreyol_games
description: "Jeux Kwazé Kréyol - Plateforme de jeux en créole martiniquais"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  path: ^1.9.0
  path_provider: ^2.1.2
  shared_preferences: ^2.5.3
  go_router: ^16.0.0
  provider: ^6.1.2
  supabase_flutter: ^2.9.2
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  confetti: ^0.7.0
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.7
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/data/

  fonts:
    - family: Permanent_Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf
